lang_map_long_name = { 1:  'Free Pascal 3.0',
                    2: 'GNU C 11.2',
                    3: 'GNU C++ 11.2',
                    7: 'Turbo Pascal',
                    9: 'Borland C',
                    10: 'Borland C++',
                    18: 'Java JDK 15',
                    22: 'PHP PHP 7.2',
                    23: 'Python 2.7',
                    24: 'Perl 5.26.1',
                    25: 'Mono C# 4.8',
                    26: 'Ruby 2.4.3',
                    27: 'Python 3.9',
                    28: 'Haskell GHC 8.2',
                    29: 'FreeBASIC 1.05',
                    30: 'PascalABC 3.7',
                    71: 'Kotlin 1.4',
                    89: 'Scala 2.13',
                    53: 'GNU Go 11.2'};

lang_array = [
	{ id : 1,
	name : "Free Pascal 3.0",
	ext : "pas",
	geshi : "pascal",
	unpriv : true,
    },
    { id : 2,
	name : "GNU C 11.2",
	ext : "c",
	geshi : "cpp",
	unpriv : true,
	priv : true,
    },
    { id : 3,
	name : "GNU C++ 11.2",
	ext : "cpp",
	geshi : "cpp",
	unpriv : true,
	priv : true,
    },
    { id : 7,
	name : "Turbo Pascal",
	ext : "",
	geshi : "pascal",
	unpriv : false,
	priv : false,
    },
    { id : 8,
	name : "Borland Delphi 6 - 14.5",
	ext : "dpr",
	geshi : "pascal",
	unpriv : false,
	priv : false,
    },
    { id : 9,
	name : "Borland C",
	ext : "",
	geshi : "c",
	unpriv : false,
	priv : false,
    },
    { id : 10,
	name : "Borland C++",
	ext : "",
	geshi : "cpp",
	unpriv : false,
	priv : false,
    },
    { id : 18,
	name : "Java JDK 15",
	ext : "java",
	geshi : "java5",
	unpriv : true,
	priv : true,
    },
    { id : 22,
	name : "PHP 7.2",
	ext : "php",
	geshi : "php",
	unpriv : true,
	priv : true,
    },
    { id : 23,
	name : "Python 2.7",
	ext : "",
	geshi : "python",
	unpriv : true,
	priv : true,
    },
    { id : 24,
	name : "Perl 5.28",
	ext : "pl",
	geshi : "perl",
	unpriv : true,
	priv : true,
    },
    { id : 25,
	name : "Mono C# 6.12",
	ext : "cs",
	geshi : "csharp",
	unpriv : true,
	priv : true,
    },
    { id : 26,
	name : "Ruby 2.5",
	ext : "rb",
	geshi : "ruby",
	unpriv : true,
	priv : true,
    },
    { id : 27,
	name : "Python 3.9",
	ext : "py",
	geshi : "python",
	unpriv : true,
	priv : true,
    },
    { id : 28,
	name : "Haskell GHC 8.2",
	ext : "hs",
	geshi : "haskell",
	unpriv : true,
	priv : true,
    },
    { id : 29,
	name : "FreeBASIC 1.05",
	ext : "bas",
	geshi : "basic",
	unpriv : true,
	priv : true,
    },
    { id : 30,
	name : "PascalABC 3.7",
	ext : "",
	geshi : "pascal",
	unpriv : true,
	priv : true,
    },
    { id : 68,
	name : "GNU C++ 5.3.1 + sanitizer",
	ext : "",
	geshi : "cpp",
	unpriv : false,
	priv : false,
    },
    {
        id : 71,
	name : "Kotlin 1.4",
	ext : "kt",
	geshi : "kt",
	unpriv : true,
	priv : true, 
    },
    {
        id : 89,
	name : "Scala 2.13",
	ext : "scala",
	geshi : "scala",
	unpriv : true,
	priv : true, 
    },
    {
        id : 53,
	name : "GNU Go 11.2",
	ext : "go",
	geshi : "go",
	unpriv : true,
	priv : true, 
    }
];
